# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndata.proto\x12\x04\x64\x61ta\"H\n\x10StockDataRequest\x12\x0e\n\x06ticker\x18\x01 \x01(\t\x12\x12\n\nstart_date\x18\x02 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x03 \x01(\t\"\xa3\x02\n\x11StockDataResponse\x12\x0e\n\x06ticker\x18\x01 \x01(\t\x12\x12\n\nstart_date\x18\x02 \x01(\t\x12\x10\n\x08\x65nd_date\x18\x03 \x01(\t\x12.\n\x06status\x18\x04 \x01(\x0e\x32\x1e.data.StockDataResponse.Status\x12*\n\x04\x64\x61ta\x18\x05 \x03(\x0b\x32\x1c.data.StockDataResponse.Data\x1a#\n\x04\x44\x61ta\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01\"W\n\x06Status\x12\x12\n\x0eINVALID_TICKER\x10\x00\x12\x16\n\x12INVALID_START_DATE\x10\x01\x12\x14\n\x10INVALID_END_DATE\x10\x02\x12\x0b\n\x07SUCCESS\x10\x03\x32G\n\x04\x44\x61ta\x12?\n\x0cgetStockData\x12\x16.data.StockDataRequest\x1a\x17.data.StockDataResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STOCKDATAREQUEST._serialized_start=20
  _STOCKDATAREQUEST._serialized_end=92
  _STOCKDATARESPONSE._serialized_start=95
  _STOCKDATARESPONSE._serialized_end=386
  _STOCKDATARESPONSE_DATA._serialized_start=262
  _STOCKDATARESPONSE_DATA._serialized_end=297
  _STOCKDATARESPONSE_STATUS._serialized_start=299
  _STOCKDATARESPONSE_STATUS._serialized_end=386
  _DATA._serialized_start=388
  _DATA._serialized_end=459
# @@protoc_insertion_point(module_scope)
