/**
 * @fileoverview gRPC-Web generated client stub for data
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.17.3
// source: data.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.data = require('./data_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.data.DataClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.data.DataPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.data.StockDataRequest,
 *   !proto.data.StockDataResponse>}
 */
const methodDescriptor_Data_getStockData = new grpc.web.MethodDescriptor(
  '/data.Data/getStockData',
  grpc.web.MethodType.UNARY,
  proto.data.StockDataRequest,
  proto.data.StockDataResponse,
  /**
   * @param {!proto.data.StockDataRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.data.StockDataResponse.deserializeBinary
);


/**
 * @param {!proto.data.StockDataRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.data.StockDataResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.data.StockDataResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.data.DataClient.prototype.getStockData =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/data.Data/getStockData',
      request,
      metadata || {},
      methodDescriptor_Data_getStockData,
      callback);
};


/**
 * @param {!proto.data.StockDataRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.data.StockDataResponse>}
 *     Promise that resolves to the response
 */
proto.data.DataPromiseClient.prototype.getStockData =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/data.Data/getStockData',
      request,
      metadata || {},
      methodDescriptor_Data_getStockData);
};


module.exports = proto.data;

